name: Bug report
description: Report an issue with react-native-unistyles
labels: 'Needs review'
body:
  - type: markdown
    attributes:
      value: |
        Before submitting a new bug/issue, please check the links below to see if there is a solution or question posted there already:
        -  Issues tab: https://github.com/jpudysz/react-native-unistyles/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
        -  Closed issues tab: https://github.com/jpudysz/react-native-unistyles/issues?q=is%3Aissue+is%3Aclosed
        -  Discussions tab: https://github.com/jpudysz/react-native-unistyles/discussions
  - type: markdown
    attributes:
      value: |
        ## Required information
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear, concise and descriptive explanation of what the bug is. Include screenshots or a video if needed by drag and dropping them to the box below.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Provide a detailed list of steps that reproduce the issue.
        Learn more about how to diagnose Unistyles problem: https://unistyl.es/v3/other/how-to-report-bug
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: input
    id: repro
    attributes:
      label: Snack or a link to a repository (optional)
      description: |
        Provide a link to the repository on GitHub that reproduces the issue.
      placeholder: Issues without a reproduction are likely to stale

  - type: input
    id: unistyles-version
    attributes:
      label: Unistyles version
      description: What version of react-native-unistyles are you using?
      placeholder: 3.0.0
    validations:
      required: true

  - type: input
    id: react-native-version
    attributes:
      label: React Native version
      description: What version of react-native are you using?
      placeholder: 0.76.0
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: Platforms
      description: On what platform your application is running on?
      multiple: true
      options:
        - Android
        - iOS
        - Web
    validations:
      required: true

  - type: dropdown
    id: expo
    attributes:
      label: Expo
      description: Are you using Expo?
      multiple: false
      options:
        - Yes
        - No
