name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        run: ./.github/actions/setup

      - name: Lint files
        run: yarn lint

      - name: Type check files
        run: yarn tsc

      - name: Run tests
        run: yarn test
